parameters:
- name: cfg
  type: object
- name: ctx
  type: object
  default: null

jobs:
- template: ./build-base.yaml
  parameters:
    cfg: ${{ parameters.cfg }}
    ctx: ${{ parameters.ctx }}
    buildSteps: []
