parameters:
- name: cfg
  type: object
- name: ctx
  type: object
  default: null

jobs:
- template: ./scan-base.yaml
  parameters:
    cfg: ${{ parameters.cfg }}
    ctx: ${{ parameters.ctx }}
    download: false
    scanSteps:
    - task: Bash@3
      displayName: Secrets Detection Scan
      inputs:
        targetType: inline
        script: |
          ls
          set -x
          appDir="${{ coalesce(parameters.cfg.path, parameters.cfg.rootPath, parameters.ctx.rootPath) }}"
          cd $appDir
          if [[ $appDir  == .* ]]; then
            appDir=`pwd`
          fi
          echo $appDir
          docker run -v $appDir:$appDir -w $appDir zricethezav/gitleaks:latest detect --verbose -f json -r ${{ coalesce(parameters.cfg.report, 'gitleaks.json') }}


    # - bash: |
    #     set -x
    #     docker run \
    #       --interactive --tty --rm \
    #       --volume "$PWD":/tmp/app \
    #       --env CI_PROJECT_DIR=/tmp/app \
    #       registry.gitlab.com/gitlab-org/security-products/analyzers/spotbugs:latest /analyzer run

    # - publish: $(System.DefaultWorkingDirectory)/gl-sast-report.json
    #   artifact: sast
    # - publish: $(System.DefaultWorkingDirectory)/gl-secret-detection-report.json
    #   artifact: secretDetection
    # - publish: $(System.DefaultWorkingDirectory)/gl-dependency-scanning-report.json
    #   artifact: dependencyScanning
